name: tools
description: Tool to publish new Universo Flutter episode
version: 0.1.0
homepage: https://universoflutter.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.17.10
